// Generated by CoffeeScript 1.2.1-pre
(function() {
  var io;

  io = (require('socket.io')).listen(7070);

  io.sockets.on('connection', function(socket) {
    return socket.emit('djs', [
      {
        name: 'nine'
      }, {
        name: 'boris'
      }
    ]);
  });

}).call(this);
